-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 00:52:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_contactos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_contactos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_contactos` DEFAULT CHARACTER SET utf8 ;
USE `db_contactos` ;

-- -----------------------------------------------------
-- Table `db_contactos`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_contactos`.`persona` (
  `pers_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pers_nombre` VARCHAR(40) NOT NULL,
  `pers_fijo` INT(11) NULL,
  `pers_celular` INT(11) NULL,
  PRIMARY KEY (`pers_id`),
  UNIQUE INDEX `pers_id_UNIQUE`(`pers_id` ASC),
  UNIQUE INDEX `pers_nombre_UNIQUE` (`pers_nombre` ASC),
  UNIQUE INDEX `pers_fijo_UNIQUE` (`pers_fijo` ASC),
  UNIQUE INDEX `pers_celular_UNIQUE` (`pers_celular` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
